add_newline = true

[character]
success_symbol = "[➜](bold #a3be8c)"
error_symbol = "[➜](bold #bf616a)"

[package]
disabled = true

[conda]
ignore_base = false
style = "bold #a3be8c"
format = "via [$symbol $environment]($style) "

[git_branch]
style = "bold #b48ead"

[python]
style = "#ebcb8b bold"

[java]
style = "red bold"

[cmd_duration]
disabled = true

[directory]
format = " [$path]($style)[$read_only]($read_only_style) "
style = "bold #88c0d0"
truncation_length = 5

[line_break]
disabled = true

[shell]
fish_indicator = ""
bash_indicator = "bash "
style = "#88c0d0"
format = "[$indicator]($style)"
disabled = false
